version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "perfumeslctdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - perfumedb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  perfumedb-data: